#!/bin/bash

# Declare the top-level directory and the program script.
projdir=~/sandbox/dmswarm-hybrid
runprog=${projdir}/run.sh

# Define the help text.
show_help() {
    printf "
This is a collection of aliases for ${runprog}.
Each case is keyed by a unique string. For example,

``$ ./run-case default``

is equivalent to

``$ cd ${projdir}``
``$ ./run.sh -Nx 8 -Ny 8 -Nz 8``
"
}

# Set up the mapping from name to function.
declare -A case_map

# Define the case functions.
run_default() {
    ./run.sh hybrid \
        -Nx 8 -Ny 8 -Nz 8 \
        -n 1 \
        --lhs-type laplacian --rhs-type sinusoidal \
        ${1}
}
case_map['default']=run_default

run_test_collection_8cubed() {
    ./run.sh hybrid \
        -Nx 8 -Ny 8 -Nz 8 \
        -Np 1024 \
        -n 1 \
        -x1 0.8 -y1 0.8 -z1 0.8 \
        --lhs-type laplacian --rhs-type sinusoidal \
        ${1}
}
case_map['test-collection-8cubed']=run_test_collection_8cubed

run_test_collisions_8cubed() {
    ./run.sh hybrid \
        -Nx 8 -Ny 8 -Nz 8 \
        -Np 1024 \
        -n 1 \
        -mi 5e-26 \
        -mn 4.6e-26 \
        -Tn 300.0 \
        -Ti 300.0 \
        -dt 1e-5 \
        -nui 5e3 \
        -x1 0.8 -y1 0.8 -z1 0.8 \
        --lhs-type laplacian --rhs-type sinusoidal \
        ${1}
}
case_map['test-collisions-8cubed']=run_test_collisions_8cubed

run_test_collection_asymmetric() {
    ./run.sh hybrid \
        -Nx 15 -Ny 10 -Nz 8 \
        -Np 1200 \
        -n 1 \
        --lhs-type laplacian --rhs-type sinusoidal \
        ${1}
}
case_map['test-collection-asymmetric']=run_test_collection_asymmetric

run_test_collection_32cubed() {
    ./run.sh hybrid \
        -Nx 64 -Ny 64 -Nz 64 \
        -Np 1048576 \
        -n 1 \
        --lhs-type laplacian --rhs-type sinusoidal \
        ${1}
}
case_map['test-collection-32cubed']=run_test_collection_32cubed

run_test_collection_long_x() {
    ./run.sh hybrid \
        -Nx 32 -Ny 8 -Nz 8 \
        -x1 4.0 -y1 1.0 -z1 1.0 \
        -Np 1000000 \
        -n 1 \
        --density-type sinusoidal \
        --lhs-type laplacian --rhs-type sinusoidal \
        ${1}
}
case_map['test-collection-long-x']=run_test_collection_long_x

run_test_rhs_indices() {
    ./run.sh hybrid \
        -Nx 64 -Ny 64 -Nz 64 \
        -n 1 \
        -Np 1048576 \
        --lhs-type laplacian \
        -vi0x 1.0 \
        -vi0y 2.0 \
        -vi0z 3.0 \
        -nue 5e4 \
        -nui 3e3 \
        -B0z 5e-5 \
        -E0y 5e-2 \
        -mi 5.0e-26 \
        -mn 4.6e-26 \
        -Te 600.0 \
        -Ti 300.0 \
        -Tn 300.0 \
        --density-type flat-sobol \
        ${1}
}
case_map['test-rhs-indices']=run_test_rhs_indices

run_test_lhs_indices() {
    ./run.sh hybrid \
        -Nx 64 -Ny 64 -Nz 64 \
        -n 1 \
        -Np 1048576 \
        --rhs-type sinusoidal \
        -mi 5.0e-26 \
        -mn 4.6e-26 \
        -Ti 300.0 \
        -Tn 300.0 \
        -nui 3e3 \
        ${1}
}
case_map['test-lhs-indices']=run_test_lhs_indices

run_gamg_basic() {
    ./run.sh hybrid \
        -ksp_monitor_short \
        -ksp_type gmres \
        -ksp_max_it 100 \
        -pc_type gamg \
        -pc_gamg_type agg \
        -Nx 16 -Ny 16 -Nz 16 -n 2 \
        ${1}
}
case_map['gamg-basic']=run_gamg_basic

run_basic_physics() {
    ./run.sh hybrid \
        -ksp_type gmres \
        -ksp_max_it 100 \
        -pc_type jacobi \
        -Nx 64 -Ny 64 -Nz 64 \
        -n 1 \
        -Nt 10 \
        -dt 1e-5 \
        -nue 5e4 \
        -nui 3e3 \
        -B0z 5e-5 \
        -E0y 5e-2 \
        -mi 5.0e-26 \
        -mn 4.6e-26 \
        -Te 600 \
        -Ti 300 \
        -Tn 300 \
        -ksp_monitor_short \
        -ksp_converged_reason \
        ${1}
}
case_map['basic-physics']=run_basic_physics

# This is intended for examining the non-zero structure of the LHS operator.
# Note that the values
# - B0x = 2.843e-7
# - B0y = 2.843e-7
# - B0z = 2.843e-7
#
# with nue = 5e4 will approximately produce
# - \kappa_x = 1.0
# - \kappa_y = 1.0
# - \kappa_z = 1.0
#
# This can be useful for testing the effect of \vec{\kappa} on the stencil.

run_solver_view_lhs() {
    ./run.sh solver \
        -Nx 8 -Ny 8 -Nz 8 \
        -n 1 \
        -ksp_type preonly \
        -pc_type lu \
        -ksp_monitor_short \
        -ksp_converged_reason \
        --lhs-type full \
        --rhs-type full \
        --view-lhs \
        --input ${projdir}/test-data/cos_xyz_8x8x8.h5 \
        -nue 5e4 \
        -nui 3e3 \
        -B0x 0.0 \
        -B0y 0.0 \
        -B0z 2.5e-5 \
        -E0x 0.0 \
        -E0y -10e-3 \
        -E0z 0.0 \
        -mi 5.0e-26 \
        -mn 4.6e-26 \
        -Te 300.0 \
        -Ti 300.0 \
        -Tn 300.0 \
        ${1}
}
case_map['solver-view-lhs']=run_solver_view_lhs

# This is intended to test FGMRES with the options given by
# https://petsc.org/release/manualpages/KSP/KSPFGMRES/
run_solver_fgmres() {
    ./run.sh solver \
        -ksp_type fgmres \
        -pc_type ksp \
        -ksp_ksp_type bcgs \
        -ksp_pc_type jacobi \
        -ksp_max_it 20 \
        -ksp_monitor_short \
        -ksp_converged_reason \
        --lhs-type full \
        --input ${projdir}/test-data/cos_x_64x64x64.h5 \
        -Nx 64 -Ny 64 -Nz 64 \
        -n 1 \
        -nue 5e4 \
        -nui 3e3 \
        -B0z 5e-5 \
        -E0y 5e-2 \
        -mi 5.0e-26 \
        -mn 4.6e-26 \
        -Te 600 \
        -Ti 300 \
        -Tn 300 \
        ${1}
}
case_map['solver-fgmres']=run_solver_fgmres

# This is intended for testing biconjugate-gradient methods (e.g., KSPBICG,
# KSPBCGS, KSPIBCGS, KSPBCGSL).
run_solver_bicg() {
    ./run.sh solver \
        -ksp_type bcgsl \
        -pc_type gamg \
        -ksp_max_it 20 \
        -ksp_monitor_short \
        -ksp_converged_reason \
        --lhs-type full \
        --input ${projdir}/test-data/cos_x_64x64x64.h5 \
        -Nx 64 -Ny 64 -Nz 64 \
        -n 1 \
        -nue 5e4 \
        -nui 3e3 \
        -B0z 5e-5 \
        -E0y 5e-2 \
        -mi 5.0e-26 \
        -mn 4.6e-26 \
        -Te 600 \
        -Ti 300 \
        -Tn 300 \
        ${1}
}
case_map['solver-bicg']=run_solver_bicg

# This is intended for testing direct solutions with MUMPS.
run_solver_mumps() {
    ./run.sh solver \
        -ksp_type preonly \
        -pc_type lu \
        -pc_factor_mat_solver_type mumps \
        -ksp_monitor_short \
        -ksp_converged_reason \
        --lhs-type full \
        --rhs-type full \
        --input ${projdir}/test-data/cos_xyz_32x32x32.h5 \
        -Nx 32 -Ny 32 -Nz 32 \
        -n 2 \
        --flux-scale 0.0 \
        -nue 5e4 \
        -nui 3e3 \
        -B0x 0.0 \
        -B0y 0.0 \
        -B0z 0.0 \
        -E0x 0.0 \
        -E0y 0.0 \
        -E0z 0.0 \
        -mi 5.0e-26 \
        -mn 4.6e-26 \
        -Te 300.0 \
        -Ti 300.0 \
        -Tn 300.0 \
        ${1}
}
case_map['solver-mumps']=run_solver_mumps

# This is intended for testing options for KSPGMRES + PCGAMG.
run_solver_gmres_gamg() {
    ./run.sh solver \
        -ksp_type gmres \
        -ksp_gmres_modifiedgramschmidt \
        -pc_type gamg \
        -pc_gamg_type agg \
        -pc_gamg_agg_nsmooths 0 \
        -pc_gamg_threshold -1 \
        -pc_gamg_threshold_scale 1 \
        -pc_gamg_aggressive_coarsening 0 \
        -pc_gamg_asm_use_agg false \
        -pc_mg_type multiplicative \
        -pc_mg_cycle_type v \
        -ksp_max_it 20 \
        -ksp_monitor_short \
        -ksp_converged_reason \
        --lhs-type full \
        --input ${projdir}/test-data/cos_xyz_64x64x64.h5 \
        -Nx 64 -Ny 64 -Nz 64 \
        -n 1 \
        -nue 5e4 \
        -nui 3e3 \
        -B0x 0.0 \
        -B0y 0.0 \
        -B0z 2.5e-5 \
        -E0x 0.0 \
        -E0y -10e-3 \
        -E0z 0.0 \
        -mi 5.0e-26 \
        -mn 4.6e-26 \
        -Te 300 \
        -Ti 300 \
        -Tn 300 \
        ${1}
}
case_map['solver-gmres-gamg']=run_solver_gmres_gamg

# This is intended mostly for checking if the stand-alone solver compiles and
# solves a toy problem, and for printing options via PETSc `-*_view` flags.
run_solver_view() {
    ./run.sh solver \
        -Nx 64 -Ny 64 -Nz 64 \
        -n 1 \
        -ksp_max_it 10 \
        -ksp_type gmres \
        -ksp_gmres_modifiedgramschmidt \
        -pc_type gamg \
        -ksp_monitor_short \
        -ksp_converged_reason \
        -ksp_view \
        -vlasov_dm_view \
        -potential_dm_view \
        --lhs-type laplacian --rhs-type sinusoidal \
        --input ${projdir}/test-data/cos_x_64x64x64.h5 \
        ${1}
}
case_map['solver-view']=run_solver_view

run_solver_debug() {
    ./run.sh solver \
        --debug \
        -ksp_type preonly \
        -pc_type lu \
        -pc_factor_mat_solver_type mumps \
        -ksp_monitor_short \
        -ksp_converged_reason \
        --lhs-type full \
        --rhs-type full \
        --input ${projdir}/test-data/cos_xyz_16x16x16.h5 \
        -Nx 16 -Ny 16 -Nz 16 \
        -n 1 \
        -nue 5e4 \
        -nui 3e3 \
        -B0x 0.0 \
        -B0y 0.0 \
        -B0z 0.0 \
        -E0x 0.0 \
        -E0y 0.0 \
        -E0z 0.0 \
        -mi 5.0e-26 \
        -mn 4.6e-26 \
        -Te 300.0 \
        -Ti 300.0 \
        -Tn 300.0 \
        --flux-scale 0.0 \
        ${1}
}
case_map['solver-debug']=run_solver_debug

# Define a function to print names of registered cases.
show_cases() {
    echo
    echo "The following cases are available:"
    for key in "${!case_map[@]}"; do
        echo "+ $key"
    done
    echo
}

# Define the function that will run a registered case.
run_case() {
    if [ -z "${1}" ]; then
        # Exit with an error if the user didn't provide a name.
        echo "Got an empty name. Exiting."
        exit 1
    fi
    if [ -v case_map[${1}] ]; then
        # Move the runtime directory to the top of the stack.
        pushd "${projdir}" &> /dev/null
        # Run the case.
        ${case_map[${1}]} --verbose
        # Remove the runtime directory from the stack.
        popd &> /dev/null
    else
        # Exit with an error if we don't recognize the case name.
        echo "Unknown case: \"${1}\""
        exit 1
    fi
}

# Read CLI input.
case "${1}" in
    -h | --help )
        show_help
        exit
        ;;
    --show-cases )
        show_cases
        exit
        ;;
    --clean )
        pushd "${projdir}/src" &> /dev/null \
        && make clean \
        && popd &> /dev/null \
        && echo "All clean!"
        exit
        ;;
    * )
        run_case "${1}"
        exit
        ;;
esac

